title: Manoa Recipes
description: An application that aids college students in finding and sharing easy-to-make recipes.
google_analytics:
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
